apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  restartPolicy: Always
  initContainers:
  - name: builder
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=/home/docker/kaniko/Dockerfile",
            "--destination=hello-world:latest"]
  containers:
  - name: hello-world
    image: hello-world:latest
    ports:
    - containerPort: 80