apiVersion: v1
kind: Pod
metadata:
  name: hello-world-deployment
spec:
  initContainers:
    - name: builder
      image: dankinah/builder
      command: ["/bin/sh", "-c", "git clone https://github.com/danielkinahan/k8s-hello-world-builder.git && cd k8s-hello-world-builder && docker build -f hello-world.Dockerfile -t hello-world:latest ."]
      volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-socket-volume
      securityContext:
        privileged: true
  containers:
    - name: hello-world
      image: hello-world:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 80
  volumes:
    - name: docker-socket-volume
      hostPath:
        path: /var/run/docker.sock