apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  initContainers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: 
    - "--context=git://github.com/danielkinahan/k8s-hello-world-builder.git"
    # - "--tar-path=/workspace/hello-world.tar"
    # - "--no-push"
    - "--destination=host.minikube.internal:5000/hello-world:latest"
    - "--skip-tls-verify"
    volumeMounts:
      - name: dockerfile-storage
        mountPath: /workspace

  containers:
  - name: hello-world
    image: hello-world:latest
    ports:
    - containerPort: 80
  restartPolicy: Never

  volumes:
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim